# Generated by Django 4.2.7 on 2024-05-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('count', models.IntegerField(verbose_name='Mahsulot soni')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Mahsulot narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Mahsulot soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
                'db_table': 'warehouse',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Transmitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Mahsulot soni')),
                ('receiver', models.CharField(max_length=100, verbose_name='Qabul qiluvchi')),
                ('receiver_date', models.DateField(verbose_name='Qabul qilingan sana')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name="Bo'lim")),
                ('image', models.ImageField(blank=True, null=True, upload_to='transmitting/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': "Jo'natilgan mahsulot",
                'verbose_name_plural': "Jo'natilgan mahsulotlar",
                'db_table': 'transmitting',
                'ordering': ['-receiver_date', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('product_count', models.IntegerField(verbose_name='Mahsulot soni')),
                ('product_price', models.FloatField(blank=True, null=True, verbose_name='Mahsulot narxi')),
                ('sender', models.CharField(max_length=100, verbose_name="Jo'natuvchi")),
                ('receiver', models.CharField(max_length=100, verbose_name='Qabul qiluvchi')),
                ('receiver_date', models.DateField(verbose_name='Qabul qilingan sana')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qabul qilingan mahsulot',
                'verbose_name_plural': 'Qabul qilingan mahsulotlar',
                'db_table': 'reception',
                'ordering': ['-receiver_date', 'product_name'],
                'indexes': [models.Index(fields=['receiver_date', 'product_name'], name='reception_receive_61c597_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['product'], name='warehouse_product_7696b7_idx'),
        ),
        migrations.AddIndex(
            model_name='transmitting',
            index=models.Index(fields=['receiver_date', 'product'], name='transmittin_receive_6239ca_idx'),
        ),
    ]
