# Generated by Django 4.2.7 on 2024-06-18 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_staff_alter_transmitting_receiver_transmitting_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmitting',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='FIO'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Bo'lim nomi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'db_table': 'department',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='department_name_9f4150_idx')],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department', verbose_name="Bo'limi"),
        ),
    ]
