# Generated by Django 4.2.7 on 2024-06-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_transmitting_receiver_alter_staff_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.department', verbose_name="Bo'limi"),
        ),
        migrations.AlterField(
            model_name='transmitting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='transmitting',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.staff', verbose_name='Qabul qiluvchi xodim'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Mahsulot'),
        ),
    ]
